const countries = [
    // Europe
    { name: "Česká republika", flag: "🇨🇿", capital: "Praha", region: "Europe", x: 515, y: 170 },
    { name: "Slovensko", flag: "🇸🇰", capital: "Bratislava", region: "Europe", x: 520, y: 175 },
    { name: "Polsko", flag: "🇵🇱", capital: "Varšava", region: "Europe", x: 525, y: 160 },
    { name: "Německo", flag: "🇩🇪", capital: "Berlín", region: "Europe", x: 505, y: 160 },
    { name: "Francie", flag: "🇫🇷", capital: "Paříž", region: "Europe", x: 490, y: 175 },
    { name: "Španělsko", flag: "🇪🇸", capital: "Madrid", region: "Europe", x: 485, y: 195 },
    { name: "Itálie", flag: "🇮🇹", capital: "Řím", region: "Europe", x: 510, y: 190 },
    { name: "Velká Británie", flag: "🇬🇧", capital: "Londýn", region: "Europe", x: 485, y: 160 },
    { name: "Irsko", flag: "🇮🇪", capital: "Dublin", region: "Europe", x: 475, y: 160 },
    { name: "Nizozemsko", flag: "🇳🇱", capital: "Amsterdam", region: "Europe", x: 495, y: 160 },
    { name: "Belgie", flag: "🇧🇪", capital: "Brusel", region: "Europe", x: 495, y: 165 },
    { name: "Švýcarsko", flag: "🇨🇭", capital: "Bern", region: "Europe", x: 500, y: 175 },
    { name: "Rakousko", flag: "🇦🇹", capital: "Vídeň", region: "Europe", x: 512, y: 175 },
    { name: "Švédsko", flag: "🇸🇪", capital: "Stockholm", region: "Europe", x: 515, y: 140 },
    { name: "Norsko", flag: "🇳🇴", capital: "Oslo", region: "Europe", x: 505, y: 140 },
    { name: "Finsko", flag: "🇫🇮", capital: "Helsinky", region: "Europe", x: 530, y: 135 },
    { name: "Dánsko", flag: "🇩🇰", capital: "Kodaň", region: "Europe", x: 505, y: 152 },
    { name: "Portugalsko", flag: "🇵🇹", capital: "Lisabon", region: "Europe", x: 475, y: 195 },
    { name: "Řecko", flag: "🇬🇷", capital: "Atény", region: "Europe", x: 530, y: 195 },
    { name: "Rumunsko", flag: "🇷🇴", capital: "Bukurešť", region: "Europe", x: 535, y: 180 },
    { name: "Maďarsko", flag: "🇭🇺", capital: "Budapešť", region: "Europe", x: 522, y: 177 },
    { name: "Bulharsko", flag: "🇧🇬", capital: "Sofie", region: "Europe", x: 532, y: 190 },
    { name: "Chorvatsko", flag: "🇭🇷", capital: "Záhřeb", region: "Europe", x: 515, y: 180 },
    { name: "Srbsko", flag: "🇷🇸", capital: "Bělehrad", region: "Europe", x: 525, y: 185 },
    { name: "Ukrajina", flag: "🇺🇦", capital: "Kyjev", region: "Europe", x: 545, y: 170 },
    { name: "Rusko", flag: "🇷🇺", capital: "Moskva", region: "Europe/Asia", x: 580, y: 150 },
    { name: "Island", flag: "🇮🇸", capital: "Reykjavík", region: "Europe", x: 470, y: 120 },
    { name: "Estonsko", flag: "🇪🇪", capital: "Tallinn", region: "Europe", x: 535, y: 140 },
    { name: "Lotyšsko", flag: "🇱🇻", capital: "Riga", region: "Europe", x: 535, y: 145 },
    { name: "Litva", flag: "🇱🇹", capital: "Vilnius", region: "Europe", x: 535, y: 150 },

    // Americas
    { name: "USA", flag: "🇺🇸", capital: "Washington D.C.", region: "North America", x: 250, y: 185 },
    { name: "Kanada", flag: "🇨🇦", capital: "Ottawa", region: "North America", x: 240, y: 145 },
    { name: "Mexiko", flag: "🇲🇽", capital: "Ciudad de México", region: "North America", x: 225, y: 220 },
    { name: "Brazílie", flag: "🇧🇷", capital: "Brasília", region: "South America", x: 315, y: 300 },
    { name: "Argentina", flag: "🇦🇷", capital: "Buenos Aires", region: "South America", x: 305, y: 360 },
    { name: "Chile", flag: "🇨🇱", capital: "Santiago", region: "South America", x: 285, y: 350 },
    { name: "Peru", flag: "🇵🇪", capital: "Lima", region: "South America", x: 270, y: 295 },
    { name: "Kolumbie", flag: "🇨🇴", capital: "Bogotá", region: "South America", x: 275, y: 260 },
    { name: "Venezuela", flag: "🇻🇪", capital: "Caracas", region: "South America", x: 295, y: 255 },
    { name: "Kuba", flag: "🇨🇺", capital: "Havana", region: "North America", x: 270, y: 230 },

    // Asia
    { name: "Čína", flag: "🇨🇳", capital: "Peking", region: "Asia", x: 680, y: 190 },
    { name: "Japonsko", flag: "🇯🇵", capital: "Tokio", region: "Asia", x: 730, y: 190 },
    { name: "Indie", flag: "🇮🇳", capital: "Nové Dillí", region: "Asia", x: 640, y: 230 },
    { name: "Jižní Korea", flag: "🇰🇷", capital: "Soul", region: "Asia", x: 715, y: 195 },
    { name: "Thajsko", flag: "🇹🇭", capital: "Bangkok", region: "Asia", x: 670, y: 245 },
    { name: "Vietnam", flag: "🇻🇳", capital: "Hanoj", region: "Asia", x: 680, y: 240 },
    { name: "Indonésie", flag: "🇮🇩", capital: "Jakarta", region: "Asia", x: 690, y: 280 },
    { name: "Malajsie", flag: "🇲🇾", capital: "Kuala Lumpur", region: "Asia", x: 675, y: 260 },
    { name: "Filipíny", flag: "🇵🇭", capital: "Manila", region: "Asia", x: 710, y: 245 },
    { name: "Singapur", flag: "🇸🇬", capital: "Singapur", region: "Asia", x: 675, y: 265 },
    { name: "Saúdská Arábie", flag: "🇸🇦", capital: "Rijád", region: "Asia", x: 570, y: 230 },
    { name: "Spojené arabské emiráty", flag: "🇦🇪", capital: "Abú Zabí", region: "Asia", x: 585, y: 235 },
    { name: "Turecko", flag: "🇹🇷", capital: "Ankara", region: "Asia/Europe", x: 545, y: 195 },
    { name: "Izrael", flag: "🇮🇱", capital: "Jeruzalém", region: "Asia", x: 550, y: 210 },
    { name: "Írán", flag: "🇮🇷", capital: "Teherán", region: "Asia", x: 585, y: 195 },
    { name: "Irák", flag: "🇮🇶", capital: "Bagdád", region: "Asia", x: 570, y: 210 },
    { name: "Pákistán", flag: "🇵🇰", capital: "Islámábád", region: "Asia", x: 620, y: 210 },
    { name: "Bangladéš", flag: "🇧🇩", capital: "Dháka", region: "Asia", x: 655, y: 235 },
    { name: "Afghánistán", flag: "🇦🇫", capital: "Kábul", region: "Asia", x: 610, y: 205 },
    { name: "Mongolsko", flag: "🇲🇳", capital: "Ulánbátar", region: "Asia", x: 680, y: 175 },

    // Africa
    { name: "Egypt", flag: "🇪🇬", capital: "Káhira", region: "Africa", x: 545, y: 230 },
    { name: "Jihoafrická republika", flag: "🇿🇦", capital: "Pretoria", region: "Africa", x: 540, y: 355 },
    { name: "Nigérie", flag: "🇳🇬", capital: "Abuja", region: "Africa", x: 500, y: 255 },
    { name: "Keňa", flag: "🇰🇪", capital: "Nairobi", region: "Africa", x: 555, y: 270 },
    { name: "Etiopie", flag: "🇪🇹", capital: "Addis Abeba", region: "Africa", x: 560, y: 255 },
    { name: "Ghana", flag: "🇬🇭", capital: "Accra", region: "Africa", x: 490, y: 260 },
    { name: "Maroko", flag: "🇲🇦", capital: "Rabat", region: "Africa", x: 485, y: 210 },
    { name: "Alžírsko", flag: "🇩🇿", capital: "Alžír", region: "Africa", x: 495, y: 200 },
    { name: "Tunisko", flag: "🇹🇳", capital: "Tunis", region: "Africa", x: 505, y: 195 },
    { name: "Libye", flag: "🇱🇾", capital: "Tripolis", region: "Africa", x: 515, y: 215 },

    // Oceania
    { name: "Austrálie", flag: "🇦🇺", capital: "Canberra", region: "Oceania", x: 750, y: 350 },
    { name: "Nový Zéland", flag: "🇳🇿", capital: "Wellington", region: "Oceania", x: 810, y: 380 },
];
